# ZSH Path
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="cloud"

# ZSH Plugins
plugins=(git)

# Oh My Zsh
source $ZSH/oh-my-zsh.sh

# Aliases
source $HOME/.aliases

# Paths
source $HOME/.path

# Functions
source $HOME/.functions