# ZSH Path
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME=intheloop

# ZSH Plugins
plugins=(git)

# Oh My Zsh
source $ZSH/oh-my-zsh.sh

# Paths
source $HOME/.path

# Aliases
source $HOME/.aliases

# Functions
source $HOME/.functions

# Completion
source $HOME/.completion
